// <auto-generated />
using System;
using G09.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G09.Migrations
{
    [DbContext(typeof(DbG09foodContext))]
    partial class DbG09foodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G09.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiViet"));

                    b.Property<string>("AnhBaiViet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLoaiMonAn")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongLike")
                        .HasColumnType("int")
                        .HasColumnName("luotthich");

                    b.HasKey("MaBaiViet")
                        .HasName("PK__BaiViet__AEDD56473B060195");

                    b.HasIndex("MaLoaiMonAn");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("BaiViet", (string)null);
                });

            modelBuilder.Entity("G09.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int?>("MaBaiViet")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBinhLuan")
                        .HasName("PK__BinhLuan__87CB66A0B5F49EF9");

                    b.HasIndex("MaBaiViet");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("BinhLuan", (string)null);
                });

            modelBuilder.Entity("G09.Models.LoaiMonAn", b =>
                {
                    b.Property<int>("MaLoaiMonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiMonAn"));

                    b.Property<string>("TenLoaiMonAn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiMonAn")
                        .HasName("PK__LoaiMonA__AF2559D340F86737");

                    b.HasIndex(new[] { "TenLoaiMonAn" }, "UQ__LoaiMonA__7AD8299C135BB907")
                        .IsUnique();

                    b.ToTable("LoaiMonAn", (string)null);
                });

            modelBuilder.Entity("G09.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuSu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D762303B0343");

                    b.HasIndex(new[] { "TenNguoiDung" }, "UQ__NguoiDun__57E5A81DADD4AFC0")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534472D9BA7")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("G09.Models.TheoDoi", b =>
                {
                    b.Property<int>("MaTheoDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheoDoi"));

                    b.Property<int?>("MaNguoiDuocTheoDoi")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiTheoDoi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaTheoDoi")
                        .HasName("PK__TheoDoi__3156C079A2F63E05");

                    b.HasIndex("MaNguoiDuocTheoDoi");

                    b.HasIndex(new[] { "MaNguoiTheoDoi", "MaNguoiDuocTheoDoi" }, "UQ__TheoDoi__1DBD570C78F5600C")
                        .IsUnique()
                        .HasFilter("[MaNguoiTheoDoi] IS NOT NULL AND [MaNguoiDuocTheoDoi] IS NOT NULL");

                    b.ToTable("TheoDoi", (string)null);
                });

            modelBuilder.Entity("G09.Models.Thich", b =>
                {
                    b.Property<int>("MaThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThich"));

                    b.Property<int?>("MaBaiViet")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaThich")
                        .HasName("PK__Thich__985232E7041EB93A");

                    b.HasIndex("MaBaiViet");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("Thich", (string)null);
                });

            modelBuilder.Entity("G09.Models.BaiViet", b =>
                {
                    b.HasOne("G09.Models.LoaiMonAn", "MaLoaiMonAnNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("MaLoaiMonAn")
                        .HasConstraintName("FK__BaiViet__MaLoaiM__52593CB8");

                    b.HasOne("G09.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__BaiViet__MaNguoi__5165187F");

                    b.Navigation("MaLoaiMonAnNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("G09.Models.BinhLuan", b =>
                {
                    b.HasOne("G09.Models.BaiViet", "MaBaiVietNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaBaiViet")
                        .HasConstraintName("FK__BinhLuan__MaBaiV__5629CD9C");

                    b.HasOne("G09.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__BinhLuan__MaNguo__571DF1D5");

                    b.Navigation("MaBaiVietNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("G09.Models.TheoDoi", b =>
                {
                    b.HasOne("G09.Models.NguoiDung", "MaNguoiDuocTheoDoiNavigation")
                        .WithMany("TheoDoiMaNguoiDuocTheoDoiNavigations")
                        .HasForeignKey("MaNguoiDuocTheoDoi")
                        .HasConstraintName("FK__TheoDoi__MaNguoi__60A75C0F");

                    b.HasOne("G09.Models.NguoiDung", "MaNguoiTheoDoiNavigation")
                        .WithMany("TheoDoiMaNguoiTheoDoiNavigations")
                        .HasForeignKey("MaNguoiTheoDoi")
                        .HasConstraintName("FK__TheoDoi__MaNguoi__5FB337D6");

                    b.Navigation("MaNguoiDuocTheoDoiNavigation");

                    b.Navigation("MaNguoiTheoDoiNavigation");
                });

            modelBuilder.Entity("G09.Models.Thich", b =>
                {
                    b.HasOne("G09.Models.BaiViet", "MaBaiVietNavigation")
                        .WithMany("Thiches")
                        .HasForeignKey("MaBaiViet")
                        .HasConstraintName("FK__Thich__MaBaiViet__5AEE82B9");

                    b.HasOne("G09.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("Thiches")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__Thich__MaNguoiDu__5BE2A6F2");

                    b.Navigation("MaBaiVietNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("G09.Models.BaiViet", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("Thiches");
                });

            modelBuilder.Entity("G09.Models.LoaiMonAn", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("G09.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("BinhLuans");

                    b.Navigation("TheoDoiMaNguoiDuocTheoDoiNavigations");

                    b.Navigation("TheoDoiMaNguoiTheoDoiNavigations");

                    b.Navigation("Thiches");
                });
#pragma warning restore 612, 618
        }
    }
}
